target/riscv: fix compilation on old gcc
gcc 4.8.4 complains

src/target/riscv/riscv-013.c:349:16: error: missing initializer
 for field 'XLEN' of 'const struct riscv_debug_reg_ctx'
 [-Werror=missing-field-initializers]
   const struct riscv_debug_reg_ctx default_context = {0};
                ^
because struct riscv_debug_reg_ctx contains 3 sub-structs.

Initialize one sub-struct to make gcc happy.

Change-Id: I58dc2544a9a6be91f3dbe5a5b700350ede71afb7
Signed-off-by: Tomas Vanek <vanekt@fbl.cz>
Reviewed-on: https://review.openocd.org/c/openocd/+/9956
Tested-by: jenkins
Reviewed-by: Antonio Borneo <borneo.antonio@gmail.com>