adapter/cmsis-dap: Improve TCP backend error reporting
When no IP address or hostname is specified, failures to connect to a
remote CMSIS-DAP adapter are not clearly explained. The only visible
output is:

  Open On-Chip Debugger 0.12.0+dev-01509-gf9212ff31 (2026-05-13-13:52)
  Licensed under GNU GPL v2
  For bug reports, read
  	http://openocd.org/doc/doxygen/bugs.html
  Info : Listening on port 6666 for tcl connections
  Info : Listening on port 4444 for telnet connections
  Error: unable to find a matching CMSIS-DAP device

The real cause is only reported in a debug message. Promote this log
message to LOG_ERROR() and reword it for better clarity.

Change-Id: Id767b477e6d820733dd2f955ff8323b6356fe796
Signed-off-by: Marc Schink <dev@zapb.de>
Reviewed-on: https://review.openocd.org/c/openocd/+/9660
Reviewed-by: Antonio Borneo <borneo.antonio@gmail.com>
Tested-by: jenkins